FROM python:3.12-alpine AS app
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install pytest requests pytest-asyncio
COPY tests/integration ./tests/integration
COPY tests.ini .
CMD ["pytest", "-m", "integration", "--disable-warnings"]